#! /bin/bash

#  This script is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License version 2 as
#  published by the Free Software Foundation.
#
#  See the COPYING and AUTHORS files for more details.

. patchfns 2>/dev/null ||
. /usr/lib/patch-scripts/patchfns 2>/dev/null ||
. $PATCHSCRIPTS_LIBDIR/patchfns 2>/dev/null ||
{
       echo "Impossible to find my library 'patchfns'."
       echo "Check your install, or go to the right directory"
       exit 1
}

usage()
{
	echo "Usage: join-patch patchname"
	exit 1
}

if [ $# -ne 1 ]
then
	usage
fi

PATCHNAME=$(stripit $1)

if ! can_apply $PATCHNAME
then
	echo Patch $PATCHNAME does not apply
	exit 1
fi

pcpatch $PATCHNAME
for i in $(files_in_patch $PATCHNAME)
do
	fpatch $i
done

patch -p1 -i $(patch_file_name $PATCHNAME) -f
