#!/bin/sh

. patchfns 2>/dev/null ||
. /usr/lib/patch-scripts/patchfns 2>/dev/null ||
. $PATCHSCRIPTS_LIBDIR/patchfns 2>/dev/null ||
{
	echo "Impossible to find my library 'patchfns'."
	echo "Check your install, or go to the right directory"
	exit 1
}

if [ $# -ne 1 ]
then
	echo "Usage prep-patch patchname"
	exit 1
fi

PATCHNAME=$(stripit $1)

xcb -s 2 < $(patch_file_name $PATCHNAME)
head -2 $(txt_file_name $PATCHNAME) | tail -1 | tr -d '\n' | xcb -s 1
