#! /bin/bash

#  This script is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License version 2 as
#  published by the Free Software Foundation.
#
#  See the COPYING and AUTHORS files for more details.


# Extract names of new files from a patch, print them out

PATCHFILE=$1
case "$PATCHFILE" in
*.gz) CMD="gzip -d < $PATCHFILE";;
*)    CMD="cat $PATCHFILE";;
esac

TMP=$(mktemp /tmp/rbp-XXXXXX)

eval $CMD | egrep '^\+\+\+.*1970|\+\+\+.*1969' > $TMP
sed -e 's@[^/]*/\([^ 	]*\).*@\1@' < $TMP | sed -e 's@^linux/@@' | sort
rm -f $TMP
