#! /bin/bash

#  This script is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License version 2 as
#  published by the Free Software Foundation.
#
#  See the COPYING and AUTHORS files for more details.

. patchfns 2>/dev/null ||
. /usr/lib/patch-scripts/patchfns 2>/dev/null ||
. $PATCHSCRIPTS_LIBDIR/patchfns 2>/dev/null ||
{
	echo "Impossible to find my library 'patchfns'."
	echo "Check your install, or go to the right directory"
	exit 1
}

if [ $# -eq 1 ]
then
       OLD=$(stripit $1)
       NEW=_$OLD
elif [ $# -eq 2 ]
then
       OLD=$(stripit $1)
       NEW=$(stripit $2)
else
       echo "Usage: rename-patch old [new]"
       exit 1
fi

mv $(pc_file_name $OLD) $(pc_file_name $NEW)
mv $(patch_file_name $OLD) $(patch_file_name $NEW)
mv $(txt_file_name $OLD) $(txt_file_name $NEW)

cvs remove $(pc_file_name $OLD) $(patch_file_name $OLD) $(txt_file_name $OLD)
cvs add $(pc_file_name $NEW) $(patch_file_name $NEW) $(txt_file_name $NEW)
