#! /bin/bash

#  This script is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License version 2 as
#  published by the Free Software Foundation.
#
#  See the COPYING and AUTHORS files for more details.

. patchfns 2>/dev/null ||
. /usr/lib/patch-scripts/patchfns 2>/dev/null ||
. $PATCHSCRIPTS_LIBDIR/patchfns 2>/dev/null ||
{
	echo "Impossible to find my library 'patchfns'."
	echo "Check your install, or go to the right directory"
	exit 1
}

usage()
{
	echo "Usage: rolled-up-patch"
	exit 1
}

if [ $# != 0 ]
then
	usage
fi

RUP=$(mktemp /tmp/rup-XXXXXX)
rm -f $RUP

for i in $(cat applied-patches)
do
	patch_name=$(stripit $i)
	files_in_patch $patch_name
done | sort | uniq > $RUP

kdiff $(cat $RUP)
rm -f $RUP
