#!/usr/bin/perl
#
# Strip whitespace on the end of GNU unified diff insertion lines.
#
# Usage:
#   cat foo | stripspace | patch -p1
#   stripspace foo | patch -p1
#
# Code fragment taken from the ARM Linux patch system, Copyright
# (C) Russell King, All Rights Reserved.
#
# This script:
#
#  Copyright (C) 2002 Russell King, All Rights Reserved.
#
#  This script is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License version 2 as
#  published by the Free Software Foundation.
#
while (<>) {
       chomp;
       s/\s+$// if m/^\+/;
       print "$_\n";
}
